version: "3"
services:
#  frontend-dev:
#    container_name: frontend-dev
#    build:
#      context: ./frontend
#      dockerfile: ../k8s/frontend/Dockerfile.dev
#    ports:
#      - "3000:3000"
#
#  frontend-prod:
#    container_name: frontend-prod
#    build:
#      context: ./frontend
#      dockerfile: ../k8s/frontend/Dockerfile.prod
#    ports:
#      - "80:80"

  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: ../k8s/backend/Dockerfile.dev
    env_file:
      - ./k8s/backend/.env.dev
    ports:
      - "5000:5000"
    networks:
      - mern-stack-net
    depends_on:
      - mongo-db
    volumes:
      - /usr/app:/

  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
