apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: database-dev-deployment
  labels:
    app: database
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      env: dev
  template:
    metadata:
      name: database
      labels:
        app: database
        env: dev
    spec:
      containers:
        - name: database
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: thesis
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: database-persistent-storage
              mountPath: /data/db

      volumes:
        - name: database-persistent-storage
          persistentVolumeClaim:
            claimName: database-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: database-dev-service
  namespace: dev
spec:
  selector:
    app: database
    env: dev
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
